/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TrabalhoFinal;

import java.awt.event.MouseEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.TableModel;

/**
 *
 * @author nicol
 */
public class TelasVeiculo extends javax.swing.JFrame {
    private Cliente selecionado = null;
    private int linhaClicada=-1;
    private ModeloTabelaCliente modeloCliente = new  ModeloTabelaCliente();// Inserindo o modelo da tabela 
    private ModeloTabelaVeiculo modeloVeiculo = new ModeloTabelaVeiculo();
    private ModeloTabelaVeiculoLocado modeloVeiculoLocado = new ModeloTabelaVeiculoLocado();
    private ModeloTabelaVeiculoVender modeloVeiculoVender = new ModeloTabelaVeiculoVender();
    private List<Cliente> clientes = new ArrayList<Cliente>();
    private List<Veiculo> veiculos = new ArrayList<Veiculo>();
    
    
    /**
     * Creates new form TelaManterCliente
     */
    public TelasVeiculo() {
        initComponents();
        loadComboBox();
        loadComboBoxEstado();
        LoadComboBoxCategoria();
        loadComboBoxModeloAutomovel();
        loadComboBoxModeloMotocicleta();
        loadComboBoxModeloVan();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        checkbox1 = new java.awt.Checkbox();
        ManterCliente = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        adicionaCliente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        atualizarCliente = new javax.swing.JButton();
        nome = new javax.swing.JTextField();
        removeCliente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        sobreNome = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cpf = new javax.swing.JTextField();
        rg = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        endereco = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelaVeiculoVender = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        categoriaSelectVender = new javax.swing.JComboBox<>();
        tipoSelectVender = new javax.swing.JComboBox<>();
        btBuscarVeiculoVender = new javax.swing.JButton();
        btVender = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaVeiculoLocado = new javax.swing.JTable();
        btDevolver = new javax.swing.JButton();
        devolverResposta = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cbxMarca = new javax.swing.JComboBox<>();
        cbxEstado = new javax.swing.JComboBox<>();
        cbxCategoria = new javax.swing.JComboBox<>();
        valorDeCompra = new javax.swing.JTextField();
        placa = new javax.swing.JTextField();
        btAutomovel = new javax.swing.JRadioButton();
        btMotocicleta = new javax.swing.JRadioButton();
        btVan = new javax.swing.JRadioButton();
        cbxAutomovel = new javax.swing.JComboBox<>();
        cbxMotocicleta = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cbxVan = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ano = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Label = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        adicionaVeiculo = new javax.swing.JButton();
        retornoInclusao = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCliente = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaVeiculo = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        buscarCliente = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        numeroDiasLocacao = new javax.swing.JTextField();
        btLocar = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        dataLocacao = new javax.swing.JTextField();
        btBuscarVeiculo = new javax.swing.JButton();
        btBuscarCliente = new javax.swing.JButton();
        tipoSelect = new javax.swing.JComboBox<>();
        categoriaSelect = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        textoLocarVeiculo = new javax.swing.JLabel();

        checkbox1.setLabel("checkbox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adicionaCliente.setText("Adicionar");
        adicionaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionaClienteActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome");

        atualizarCliente.setText("Editar");
        atualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarClienteActionPerformed(evt);
            }
        });

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });

        removeCliente.setText("Excluir");
        removeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeClienteActionPerformed(evt);
            }
        });

        jLabel4.setText("Sobrenome");

        jButton4.setText("Listar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        sobreNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreNomeActionPerformed(evt);
            }
        });

        tabela.setModel(modeloCliente);
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela);

        jLabel5.setText("CPF");

        jLabel6.setText("RG");

        jLabel7.setText("Endereço");

        cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfActionPerformed(evt);
            }
        });

        rg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Adicionar Cliente");

        endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(64, 64, 64))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(endereco))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nome)
                                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sobreNome, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(adicionaCliente)
                                .addGap(47, 47, 47)
                                .addComponent(atualizarCliente)
                                .addGap(53, 53, 53)
                                .addComponent(removeCliente)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(28, 28, 28))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(sobreNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionaCliente)
                    .addComponent(atualizarCliente)
                    .addComponent(removeCliente)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ManterCliente.addTab("Cliente", jPanel2);

        jLabel20.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 0, 102));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Vender Veiculo");

        tabelaVeiculoVender.setModel(modeloVeiculoVender);
        tabelaVeiculoVender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaVeiculoVenderMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tabelaVeiculoVender);

        jLabel25.setText("Buscar Veiculo");

        categoriaSelectVender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Popular", "Intermediario", "Luxo" }));

        tipoSelectVender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automovel", "Motocicleta", "Van" }));
        tipoSelectVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoSelectVenderActionPerformed(evt);
            }
        });

        btBuscarVeiculoVender.setText("Buscar");
        btBuscarVeiculoVender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btBuscarVeiculoVenderMouseClicked(evt);
            }
        });

        btVender.setText("Vender");
        btVender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btVenderMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(categoriaSelectVender, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(tipoSelectVender, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btBuscarVeiculoVender))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)))
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btVender, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(240, 240, 240))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(categoriaSelectVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoSelectVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarVeiculoVender))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btVender, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(368, Short.MAX_VALUE))
        );

        ManterCliente.addTab("Vender Veiculo", jPanel5);

        jLabel21.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 0, 102));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Devolver Veiculo");

        tabelaVeiculoLocado.setModel(modeloVeiculoLocado);
        tabelaVeiculoLocado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaVeiculoLocadoMouseClicked(evt);
            }
        });
        tabelaVeiculoLocado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaVeiculoLocadoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabelaVeiculoLocado);

        btDevolver.setText("Devolver");
        btDevolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDevolverMouseClicked(evt);
            }
        });
        btDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDevolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(btDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(devolverResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(devolverResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );

        ManterCliente.addTab("Devolver Veiculo", jPanel6);

        cbxMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMarcaActionPerformed(evt);
            }
        });

        cbxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEstadoActionPerformed(evt);
            }
        });

        cbxCategoria.setToolTipText("");
        cbxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoriaActionPerformed(evt);
            }
        });

        valorDeCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorDeCompraActionPerformed(evt);
            }
        });

        placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placaActionPerformed(evt);
            }
        });

        buttonGroup1.add(btAutomovel);
        btAutomovel.setText("Automóvel");
        btAutomovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAutomovelActionPerformed(evt);
            }
        });

        buttonGroup1.add(btMotocicleta);
        btMotocicleta.setText("Motocicleta");
        btMotocicleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMotocicletaActionPerformed(evt);
            }
        });

        buttonGroup1.add(btVan);
        btVan.setText("Van");
        btVan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVanActionPerformed(evt);
            }
        });

        cbxAutomovel.setEnabled(false);
        cbxAutomovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAutomovelActionPerformed(evt);
            }
        });

        cbxMotocicleta.setEnabled(false);

        jLabel10.setText("Modelo Motocicleta");

        cbxVan.setEnabled(false);

        jLabel11.setText("Modelo Van ");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Incluir Veículos");

        ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Incluir Veículo");

        Label.setText("Marca");

        jLabel13.setText("Ano");

        jLabel14.setText("Estado");

        jLabel15.setText("Categoria");

        jLabel16.setText("Modelo Automovel");

        jLabel17.setText("Valor de Compra");

        jLabel18.setText("Placa");

        adicionaVeiculo.setText("Incluir");
        adicionaVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionaVeiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(btAutomovel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(valorDeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbxAutomovel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(24, 24, 24)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btMotocicleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btVan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(237, 237, 237))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxMotocicleta, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(13, 13, 13)
                                .addComponent(cbxVan, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(108, 108, 108))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(placa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(25, 25, 25)
                                .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Label, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbxEstado, 0, 174, Short.MAX_VALUE)
                                        .addComponent(cbxCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(cbxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(430, 430, 430))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(retornoInclusao, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(adicionaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(197, 197, 197))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btAutomovel)
                    .addComponent(btMotocicleta)
                    .addComponent(btVan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label)
                    .addComponent(cbxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cbxAutomovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(cbxVan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxMotocicleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(valorDeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adicionaVeiculo)
                .addGap(74, 74, 74)
                .addComponent(retornoInclusao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        ManterCliente.addTab("Incluir Veiculo", jPanel3);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 0, 102));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Locar Veiculo");

        jLabel2.setText("Buscar Cliente:");

        tabelaCliente.setModel(modeloCliente);
        tabelaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaCliente);

        tabelaVeiculo.setModel(modeloVeiculo);
        tabelaVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaVeiculoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaVeiculo);

        jLabel22.setText("Buscar Veiculo");

        buscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarClienteActionPerformed(evt);
            }
        });

        jLabel23.setText("Numero de dias de locação:");

        numeroDiasLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroDiasLocacaoActionPerformed(evt);
            }
        });

        btLocar.setText("Locar");
        btLocar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btLocarMouseClicked(evt);
            }
        });
        btLocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLocarActionPerformed(evt);
            }
        });

        jLabel24.setText("Data de locação:");

        dataLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataLocacaoActionPerformed(evt);
            }
        });

        btBuscarVeiculo.setText("Buscar");
        btBuscarVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btBuscarVeiculoMouseClicked(evt);
            }
        });

        btBuscarCliente.setText("Buscar");
        btBuscarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btBuscarClienteMouseClicked(evt);
            }
        });

        tipoSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automovel", "Motocicleta", "Van" }));
        tipoSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoSelectActionPerformed(evt);
            }
        });

        categoriaSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Popular", "Intermediario", "Luxo" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numeroDiasLocacao, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(dataLocacao))
                .addGap(319, 319, 319))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(buscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btBuscarCliente))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(categoriaSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tipoSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btBuscarVeiculo)))
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btLocar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(217, 217, 217))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(buscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarCliente))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(btBuscarVeiculo)
                    .addComponent(tipoSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoriaSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(numeroDiasLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(dataLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btLocar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        ManterCliente.addTab("Locar Veiculo", jPanel4);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 0, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Locadora de Veículos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ManterCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoLocarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManterCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textoLocarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void sobreNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sobreNomeActionPerformed

    private void atualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarClienteActionPerformed
       if(linhaClicada != -1){
            Cliente c = modeloCliente.getCliente(linhaClicada);
            c.setNome(nome.getText());
            c.setSobreNome(sobreNome.getText());
            c.setRg(rg.getText());
            c.setCpf(cpf.getText());
            c.setEndereco(endereco.getText());

            modeloCliente.fireTableRowsUpdated(linhaClicada, linhaClicada);
            
            // For para interar sobre a lista do clientes banco de dados
            for (Cliente cliente: this.clientes) {
                if (cliente.getCpf().equals(c.getCpf())) {
                    int indice = this.clientes.indexOf(cliente);
                    this.clientes.set(indice, c);
                }
            }
    
       }
    }//GEN-LAST:event_atualizarClienteActionPerformed

    private void adicionaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionaClienteActionPerformed
        Cliente c = new Cliente (nome.getText(),sobreNome.getText(), rg.getText(), cpf.getText(),endereco.getText());
        this.clientes.add(c);
        modeloCliente.adicionaCliente(this.clientes);
        nome.setText("");
        sobreNome.setText("");
        rg.setText("");
        cpf.setText("");
        endereco.setText("");
        
    }//GEN-LAST:event_adicionaClienteActionPerformed

    private void cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfActionPerformed

    private void rgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rgActionPerformed

    private void enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoActionPerformed

    private void removeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeClienteActionPerformed
       int indice = modeloCliente.removeCliente(selecionado);
       
        nome.setText("");
        sobreNome.setText("");
        rg.setText("");
        cpf.setText("");
        endereco.setText("");
        this.clientes.remove(indice);
    }//GEN-LAST:event_removeClienteActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        linhaClicada = tabela.rowAtPoint(evt.getPoint());
        Cliente cl  = modeloCliente.getCliente(linhaClicada);
        
        Cliente c = modeloCliente.getCliente(tabela.getSelectedRow());
      
        nome.setText(c.getNome());
        sobreNome.setText(c.getSobreNome());
        rg.setText(c.getCpf());
        cpf.setText(c.getRg());
        endereco.setText(c.getEndereco());
       
        selecionado = c;
    }//GEN-LAST:event_tabelaMouseClicked

    private void adicionaVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionaVeiculoActionPerformed
      
       String smarca = this.cbxMarca.getSelectedItem().toString();  //converte marca para string
       String sestado = this.cbxEstado.getSelectedItem().toString();
       String scategoria = this.cbxCategoria.getSelectedItem().toString();
       double dvalor = Double.parseDouble(this.valorDeCompra.getText());
       
       int iano = Integer.parseInt(this.ano.getText());
       Veiculo a = null;
       
       if (btAutomovel.isSelected()) {
           String smodelo = this.cbxAutomovel.getSelectedItem().toString();
            a = new Automovel(ModeloAutomovel.valueOf(smodelo),Marca.valueOf(smarca),Estado.valueOf(sestado),Categoria.valueOf(scategoria),null, dvalor, placa.getText().toString(),iano);
       }
       if (btMotocicleta.isSelected()) {
           String smodelo = this.cbxMotocicleta.getSelectedItem().toString();
            a = new Motocicleta(ModeloMotocicleta.valueOf(smodelo),Marca.valueOf(smarca),Estado.valueOf(sestado),Categoria.valueOf(scategoria),null, dvalor, placa.getText().toString(),iano);
       } 
       if (btVan.isSelected()){
           String smodelo = this.cbxVan.getSelectedItem().toString();
           a = new Van (ModeloVan.valueOf(smodelo),Marca.valueOf(smarca),Estado.valueOf(sestado),Categoria.valueOf(scategoria),null, dvalor, placa.getText().toString(),iano);
       }
       
   
       this.veiculos.add(a);
       modeloVeiculo.adicionaVeiculo(this.veiculos);

       this.retornoInclusao.setText("Veiculo incluído com sucesso!");
    }//GEN-LAST:event_adicionaVeiculoActionPerformed

    private void anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anoActionPerformed

    private void cbxAutomovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAutomovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxAutomovelActionPerformed

    private void btVanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVanActionPerformed
        if (btVan.isSelected()){
            cbxAutomovel.setEnabled(false);
            cbxMotocicleta.setEnabled(false);
            cbxVan.setEnabled(true);
        }
    }//GEN-LAST:event_btVanActionPerformed

    private void btMotocicletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMotocicletaActionPerformed
        if (btMotocicleta.isSelected()){
            cbxAutomovel.setEnabled(false);
            cbxMotocicleta.setEnabled(true);
            cbxVan.setEnabled(false);
        }
    }//GEN-LAST:event_btMotocicletaActionPerformed

    private void btAutomovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAutomovelActionPerformed
        if (btAutomovel.isSelected()){
            cbxAutomovel.setEnabled(true);
            cbxMotocicleta.setEnabled(false);
            cbxVan.setEnabled(false);
        }
    }//GEN-LAST:event_btAutomovelActionPerformed

    private void placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placaActionPerformed

    private void valorDeCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorDeCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorDeCompraActionPerformed

    private void cbxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCategoriaActionPerformed

    private void cbxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEstadoActionPerformed

    private void cbxMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMarcaActionPerformed

    }//GEN-LAST:event_cbxMarcaActionPerformed

    private void numeroDiasLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroDiasLocacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroDiasLocacaoActionPerformed

    private void btLocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLocarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLocarActionPerformed

    private void dataLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataLocacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataLocacaoActionPerformed

    private void btBuscarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBuscarClienteMouseClicked
        
        List<Cliente> clientesProcurados = new ArrayList<Cliente>();
        for(Cliente cliente: this.clientes) {
            if(cliente.getNome().equals(buscarCliente.getText())) {
               clientesProcurados.add(cliente);
            }
            if (cliente.getSobreNome().equals(buscarCliente.getText())) {
                clientesProcurados.add(cliente);
            }
            if (cliente.getCpf().equals(buscarCliente.getText())) {
                clientesProcurados.add(cliente);
            }
        }
        
        this.modeloCliente.atualizarTabela(clientesProcurados);
            
        // TODO add your handling code here:
    }//GEN-LAST:event_btBuscarClienteMouseClicked

    private void buscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarClienteActionPerformed

    private void btBuscarVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBuscarVeiculoMouseClicked
           
        List<Veiculo> veiculosProcurados = new ArrayList<Veiculo>();
        for(Veiculo veiculo: this.veiculos) {
           if(veiculo.getEstado().toString().toLowerCase().equals("disponivel")) {
                if(this.tipoSelect.getSelectedItem().toString().toLowerCase().equals("automovel")) {
                    if(veiculo instanceof Automovel) {
                         if (veiculo.getCategoria().equals(Categoria.valueOf(this.categoriaSelect.getSelectedItem().toString().toUpperCase()))) {
                             veiculosProcurados.add(veiculo);
                         }
                    }
                } 
                
                if(this.tipoSelect.getSelectedItem().toString().toLowerCase().equals("motocicleta")) {
                    if(veiculo instanceof Motocicleta) {
                         if (veiculo.getCategoria().equals(Categoria.valueOf(this.categoriaSelect.getSelectedItem().toString().toUpperCase()))) {
                             veiculosProcurados.add(veiculo);
                         }
                    }
                }
                
                if(this.tipoSelect.getSelectedItem().toString().toLowerCase().equals("van")) {
                    if(veiculo instanceof Van) {
                         if (veiculo.getCategoria().equals(Categoria.valueOf(this.categoriaSelect.getSelectedItem().toString().toUpperCase()))) {
                             veiculosProcurados.add(veiculo);
                         }
                    }
                }
           }
        }
        this.modeloVeiculo.atualizarTabela(veiculosProcurados);
    }//GEN-LAST:event_btBuscarVeiculoMouseClicked

    private int tabelaVeiculoFiltradaLinha;
    private void tabelaVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaVeiculoMouseClicked
        tabelaVeiculoFiltradaLinha = tabelaVeiculo.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_tabelaVeiculoMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        this.modeloCliente.atualizarTabela(this.clientes);
    }//GEN-LAST:event_jButton4MouseClicked

    private void tipoSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoSelectActionPerformed

    private void btLocarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLocarMouseClicked
        int diasLocacao = Integer.parseInt(this.numeroDiasLocacao.getText());
        List<Veiculo> veiculosLocados = new ArrayList<Veiculo>();
        
        Cliente cliente = null;
        
        for(Cliente clientes: this.clientes) {
            if (clientes.getCpf().equals(tabelaCliente.getValueAt(tabelaClienteFiltradaLinha, 2))) {
                cliente = clientes;
            }
        }
        
        for(Veiculo veiculo: this.veiculos) {
            if (veiculo.getEstado().toString().toLowerCase().equals("locado")) {
                veiculosLocados.add(veiculo);
            }
            
            if (veiculo.getPlaca().equals(tabelaVeiculo.getValueAt(tabelaVeiculoFiltradaLinha, 1))) {
                DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
                try {
                    Date date = formatter.parse(this.dataLocacao.getText());
                    Calendar calendar = Calendar.getInstance();
                    calendar.setTime(date);
                    veiculo.locar(diasLocacao, calendar, cliente);
                    this.textoLocarVeiculo.setText("Veiculo locado!");
                    veiculosLocados.add(veiculo);
                    this.modeloVeiculoLocado.atualizarTabela(veiculosLocados);
                } catch (ParseException e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_btLocarMouseClicked

    private int tabelaClienteFiltradaLinha;
    private void tabelaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClienteMouseClicked
       tabelaClienteFiltradaLinha = tabelaCliente.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_tabelaClienteMouseClicked

    private void btDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDevolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDevolverActionPerformed

    int tabelaVeiculosLocadosLinha;
    private void tabelaVeiculoLocadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaVeiculoLocadoMouseClicked
        tabelaVeiculosLocadosLinha = tabelaVeiculoLocado.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_tabelaVeiculoLocadoMouseClicked

    private void btDevolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDevolverMouseClicked
        for(Veiculo veiculo: this.veiculos) {
            if(veiculo.getPlaca().equals(tabelaVeiculoLocado.getValueAt(tabelaVeiculosLocadosLinha, 1))) {
                veiculo.devolver();
                modeloVeiculoLocado.removeVeiculoLocado(veiculo);
                this.devolverResposta.setText("Veiculo devolvido!");
            }
        }
    }//GEN-LAST:event_btDevolverMouseClicked

    private void tipoSelectVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoSelectVenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoSelectVenderActionPerformed

    private void btBuscarVeiculoVenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBuscarVeiculoVenderMouseClicked
       List<Veiculo> veiculosProcurados = new ArrayList<Veiculo>();
        for(Veiculo veiculo: this.veiculos) {
           if(veiculo.getEstado().toString().toLowerCase().equals("disponivel")) {
                if(this.tipoSelectVender.getSelectedItem().toString().toLowerCase().equals("automovel")) {
                    if(veiculo instanceof Automovel) {
                         if (veiculo.getCategoria().equals(Categoria.valueOf(this.categoriaSelectVender.getSelectedItem().toString().toUpperCase()))) {
                             veiculosProcurados.add(veiculo);
                         }
                    }
                } 
                
                if(this.tipoSelectVender.getSelectedItem().toString().toLowerCase().equals("motocicleta")) {
                    if(veiculo instanceof Motocicleta) {
                         if (veiculo.getCategoria().equals(Categoria.valueOf(this.categoriaSelectVender.getSelectedItem().toString().toUpperCase()))) {
                             veiculosProcurados.add(veiculo);
                         }
                    }
                }
                
                if(this.tipoSelectVender.getSelectedItem().toString().toLowerCase().equals("van")) {
                    if(veiculo instanceof Van) {
                         if (veiculo.getCategoria().equals(Categoria.valueOf(this.categoriaSelectVender.getSelectedItem().toString().toUpperCase()))) {
                             veiculosProcurados.add(veiculo);
                         }
                    }
                }
           }
        }
        this.modeloVeiculoVender.atualizarTabela(veiculosProcurados);
    }//GEN-LAST:event_btBuscarVeiculoVenderMouseClicked

    private int tabelaVeiculosVenderLinha;
    private void tabelaVeiculoVenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaVeiculoVenderMouseClicked
       tabelaVeiculosVenderLinha = tabelaVeiculoVender.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_tabelaVeiculoVenderMouseClicked

    private void btVenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVenderMouseClicked
        for(Veiculo veiculo: this.veiculos) {
            if (veiculo.getPlaca().equals(modeloVeiculo.getValueAt(tabelaVeiculosVenderLinha, 1))) {
                veiculo.vender();
            }
        }
        
        List<Veiculo> veiculosVendidos = new ArrayList<Veiculo>();
        for(Veiculo veiculo: this.veiculos) {
           if(veiculo.getEstado().toString().toLowerCase().equals("disponivel")) {
                if(this.tipoSelectVender.getSelectedItem().toString().toLowerCase().equals("automovel")) {
                    if(veiculo instanceof Automovel) {
                         if (veiculo.getCategoria().equals(Categoria.valueOf(this.categoriaSelectVender.getSelectedItem().toString().toUpperCase()))) {
                             veiculosVendidos.add(veiculo);
                         }
                    }
                } 
                
                if(this.tipoSelectVender.getSelectedItem().toString().toLowerCase().equals("motocicleta")) {
                    if(veiculo instanceof Motocicleta) {
                         if (veiculo.getCategoria().equals(Categoria.valueOf(this.categoriaSelectVender.getSelectedItem().toString().toUpperCase()))) {
                             veiculosVendidos.add(veiculo);
                         }
                    }
                }
                
                if(this.tipoSelectVender.getSelectedItem().toString().toLowerCase().equals("van")) {
                    if(veiculo instanceof Van) {
                         if (veiculo.getCategoria().equals(Categoria.valueOf(this.categoriaSelectVender.getSelectedItem().toString().toUpperCase()))) {
                             veiculosVendidos.add(veiculo);
                         }
                    }
                }
           }
        }
        this.modeloVeiculoVender.atualizarTabela(veiculosVendidos);
    }//GEN-LAST:event_btVenderMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void  main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelasVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelasVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelasVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelasVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelasVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label;
    private javax.swing.JTabbedPane ManterCliente;
    private javax.swing.JButton adicionaCliente;
    private javax.swing.JButton adicionaVeiculo;
    private javax.swing.JTextField ano;
    private javax.swing.JButton atualizarCliente;
    private javax.swing.JRadioButton btAutomovel;
    private javax.swing.JButton btBuscarCliente;
    private javax.swing.JButton btBuscarVeiculo;
    private javax.swing.JButton btBuscarVeiculoVender;
    private javax.swing.JButton btDevolver;
    private javax.swing.JButton btLocar;
    private javax.swing.JRadioButton btMotocicleta;
    private javax.swing.JRadioButton btVan;
    private javax.swing.JButton btVender;
    private javax.swing.JTextField buscarCliente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> categoriaSelect;
    private javax.swing.JComboBox<String> categoriaSelectVender;
    private javax.swing.JComboBox<ModeloAutomovel> cbxAutomovel;
    private javax.swing.JComboBox<Categoria> cbxCategoria;
    private javax.swing.JComboBox<Estado> cbxEstado;
    private javax.swing.JComboBox<Marca> cbxMarca;
    private javax.swing.JComboBox<ModeloMotocicleta> cbxMotocicleta;
    private javax.swing.JComboBox<ModeloVan> cbxVan;
    private java.awt.Checkbox checkbox1;
    private javax.swing.JTextField cpf;
    private javax.swing.JTextField dataLocacao;
    private javax.swing.JLabel devolverResposta;
    private javax.swing.JTextField endereco;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField numeroDiasLocacao;
    private javax.swing.JTextField placa;
    private javax.swing.JButton removeCliente;
    private javax.swing.JLabel retornoInclusao;
    private javax.swing.JTextField rg;
    private javax.swing.JTextField sobreNome;
    private javax.swing.JTable tabela;
    private javax.swing.JTable tabelaCliente;
    private javax.swing.JTable tabelaVeiculo;
    private javax.swing.JTable tabelaVeiculoLocado;
    private javax.swing.JTable tabelaVeiculoVender;
    private javax.swing.JLabel textoLocarVeiculo;
    private javax.swing.JComboBox<String> tipoSelect;
    private javax.swing.JComboBox<String> tipoSelectVender;
    private javax.swing.JTextField valorDeCompra;
    // End of variables declaration//GEN-END:variables

   private void loadComboBox() {
        cbxMarca.setModel(new DefaultComboBoxModel<>(Marca.values()));
    }

    private void loadComboBoxEstado() {
        cbxEstado.setModel(new DefaultComboBoxModel<>(Estado.values()));
    }

    private void LoadComboBoxCategoria() {
        cbxCategoria.setModel(new DefaultComboBoxModel<>(Categoria.values()));
    }
    
    private void loadComboBoxModeloAutomovel() {
      
        cbxAutomovel.setModel(new DefaultComboBoxModel<>(ModeloAutomovel.values()));
       
    }

    private void loadComboBoxModeloMotocicleta() {
        cbxMotocicleta.setModel(new DefaultComboBoxModel<>(ModeloMotocicleta.values()));
    }

    private void loadComboBoxModeloVan() {
        cbxVan.setModel(new DefaultComboBoxModel<>(ModeloVan.values()));
    }
}
